### ISSUE TITLE
Error in watcher "defaultPlace"

### ISSUE THREAD

**Issue by ethanclevenger91** [xkjyeah/vue-google-maps#8] opened 2016-11-30 21:55 UTC
So here's my input:

```<place-input :defaultPlace="value" @place_changed="updateValue" className="form-control" :id="label + 'Directions'"></place-input>```

And when I type in it and select one of the available options, I get:

```
[Vue warn]: Error in watcher "defaultPlace" 
(found in component <GmapPlaceInput> at E:\dev\beerpilgrimage\node_modules\vue2-google-maps\dist\components\placeInput.vue)

Uncaught (in promise) TypeError: googleMapsElement[setMethodName] is not a function
    at VueComponent.vueElement.$watch.deep (eval at <anonymous> (main.js:126), <anonymous>:39:39)
    at Watcher.run (eval at <anonymous> (main.js:132), <anonymous>:1713:19)
    at flushSchedulerQueue (eval at <anonymous> (main.js:132), <anonymous>:1517:13)
    at Array.eval (eval at <anonymous> (main.js:132), <anonymous>:380:20)
    at nextTickHandler (eval at <anonymous> (main.js:132), <anonymous>:330:16)
```

The error appears to be in propsBinder.js at line 39?

**Comment by xkjyeah** [comment] 2016-12-01 04:03
This has been fixed in v 0.4.3.

Run `npm install vue2-google-maps@latest`.

**Comment by xkjyeah** [comment] 2016-12-01 04:04
On the other hand, when using defaultPlace no lat-lng will be available. If this isn't a problem then we can close the issue.

**Comment by ethanclevenger91** [comment] 2016-12-02 22:16
Works for me, but that's just me. If I recall correctly, on the original, defaultPlace could be passed a [place object](https://developers.google.com/maps/documentation/javascript/3.exp/reference#Place). Any reason this is no longer the case?

**Comment by xkjyeah** [comment] 2016-12-03 11:27
How useful is it? I didn't know it's possible to create a Place object
directly. If it were possible then it might make sense to allow the Place
object to be passed in.

On 3 Dec 2016 07:16, "Ethan Clevenger" <notifications@github.com> wrote:

Works for me, but that's just me. If I recall correctly, on the original,
defaultPlace could be passed a place object
<https://developers.google.com/maps/documentation/javascript/3.exp/reference#Place>.
Any reason this is no longer the case?

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/xkjyeah/vue-google-maps/issues/8#issuecomment-264577369>,
or mute the thread

**Comment by ethanclevenger91** [comment] 2016-12-05 18:43
Okay actually it would have [taken one of these](https://developers.google.com/maps/documentation/javascript/3.exp/reference#PlaceResult). Anyway, correct me if I'm wrong, but a JS object is an object is an object, so I always just dummied up a vanilla object and passed that:

```
var defaultPlace {
   formatted_address: '123 45th St'
}
```

And the input component used formatted_address. I liked it because when using Vuex, I'm directly saving the result of `place_changed` to my store - the full object. If the input expects a string rather than this object, I have to pass it a computed property that just gets the title. Not the end of the world, and that may even work better for a lot of people. It's arguably more intuitive to set up, but in my opinion, less intuitive to update. Probably worth getting more feedback.

**Comment by xkjyeah** [comment] 2016-12-17 04:17
I've pushed an update in 0.4.6. This update basically binds :default-place to the :value of the &lt;input. 

[Example here](http://xkjyeah.github.io/vue-google-maps/basic-place-input.html)

-----
I made a couple of design choices in this library, please feel free to critique.
1. When designing the APIs for vue2-google-maps, I wanted a closer correspondence between the Google Maps API the library APIs. This means that the library will not actively translate google.maps.LatLng objects to LatLng literals. Reasons for this are:
    a. To save some computational cycles -- every translation is overhead, whether or not the object is finally used.
    b. To avoid unexpected behaviour (e.g. LatLng object in mouse events, LatLng literal in position_changed events -- resulting in API inconsistencies)
2. For the Autocomplete, Google Maps API doesn't support `setPlace()`. The only way to show something in the text box is to set its value directly. The correct way about this is to write the Place Input as a directive. This would be the thinnest wrapper around the API. However, doing so in Vue is tricky since directives are very limited in functionality. Therefore I have opted to bind the :value of the input to a parent-level prop (current :default-place, but I probably should rename it).

In any case, you can now achieve your desired behaviour by binding :default-place to the formatted address:
```
data: {
   selectedPlace: {
      formatted_address: '18 Broad Street'
   }
}
```
```
template: `
    <gmap-place-input :default-place="selectedPlace.formatted_address" />
```
I think this should be sufficient to meet your needs. Let me know if that isn't the case.

**Closed as completed** 2016-12-24 14:07 UTC
