### ISSUE TITLE
Issue with two-way binding in map center example

### ISSUE THREAD

**Issue by JoseGoncalves** [xkjyeah/vue-google-maps#325] opened 2018-02-14 08:59 UTC
Currently, in example http://xkjyeah.github.io/vue-google-maps/test-map-center-twoway.html , the pan can only be done in very small steps.
What is the proper way to have the map's center position constantly updated in our model when we move the map?

**Comment by xkjyeah** [comment] 2018-02-14 10:30
Hmmmm that seems like a regression. I'll need to check it out.

**Comment by xkjyeah** [comment] 2018-02-14 10:45
A good way is actually to:

1. Bind the map's centre to a hidden property (e.g. mapCentre)
2. Bind the input boxes to a another property (e.g. inputBoxLat,
inputBoxLng)
3. Add an event handler to update mapCentre, only when the user physically
interacts with the input box e.g.
<input @change="mapCentre.lat = inputBoxLat">

This way we won't have unintended circular updates on the map being
triggered.

On 14 Feb 2018 18:30, "Daniel Sim" <daniel.ssq89@gmail.com> wrote:

Hmmmm that seems like a regression. I'll need to check it out.

**Comment by JoseGoncalves** [comment] 2018-02-14 13:20
Yeahh, we could do it like you tell, but that it's not really a two-way data binding.
It's using two objects each one providing a one-way binding.
Doing the job, it does not look a clean solution to me.
It would not be better to hide that logic inside the map component?

**Comment by xkjyeah** [comment] 2018-02-14 13:42
Actually, that is the cleaner solution. Two-way binding has serious
problems. The main problem is it is not clear which component owns the
data. This is the reason why the Vue Library does not recommend two-way
binding.

The main problem here is that the center position reported by the map may
not be the same position that you pass into the map. I.e.

map.setCenter(coords1)
const coords2 = map.getCenter()
coords1.lat() == coords2.lat() // usually false

In this case should the text box reflect the coordinates that you pass into
the map, or should it reflect the coordinates that is being shown on the
map? When should the text box start to reflect the data in the map?

The answer here is obvious: the text box should reflect the coordinates of
the map, unless you change the value inside the text box. This is exactly
the behavior that is described in the code I provided

I will still look into the bug.

**Comment by xkjyeah** [comment] 2018-02-14 15:14
Should be fixed in v0.8.5

**Comment by Dylan-Chapman** [comment] 2018-02-14 20:38
I'm still having the same problem in v0.8.5. Just me?

**Comment by JoseGoncalves** [comment] 2018-02-14 23:00
I confirm that v0.8.5 still has the issue that I reported.

**Comment by xkjyeah** [comment] 2018-02-15 16:49
Ugh sorry guys. Didn't test this thoroughly enough.

The root of the problem is that there doesn't seem to be a good way to identify whether the a change of lat/lng originates from the user, or from a dependent component.

A naive implementation will result in an infinite loop when the user pans the map:
`center_changed` -> update the lat/lng in event handler -> `$watch` triggered -> `center_changed` -> update the lat/lng in event handler -> ...

The solution currently implemented cuts the loop by adding a counter. But this only works when you update the lat/lng in the text box:
update the lat/lng in text box -> **counter++** -> `center_changed` -> **counter--**, `$watch` **not** triggered

However, it doesn't work for panning the map:
`center_changed` -> **counter--** -> update lat/lng -> `$watch` triggered because counter is zero  -> `setCenter()` called on the map and panning breaks.

If you have any suggestions how to break this loop, I'll try to incorporate. Otherwise I'll have to put it as a wontfix for now. I'll also replace the example with a working one.

**Comment by Dylan-Chapman** [comment] 2018-02-15 22:18
Unless I'm doing something wrong, the problem I'm having is related, but IMO would be weird to be labeled as a wontfix. I simply have a map with ```:center="mapCenter"``` and ```@center_changed="center => mapCenter = center"```. This produces the same problem. Unless there's another way for the map's ```center``` property to be reactive, this seems like it would be a fairly common scenario?

**Comment by xkjyeah** [comment] 2018-02-16 01:57
Actually, in many (most?) use cases, people do not need to set the center of the map with a text box.

The rule here is, at least with the current version of Google Maps, is that in the midst of panning a map, **Thou shalt not call `setCenter`**. For in the day you do that, **your pan will break**.

I can't remember if this was the case with the older version of Google Maps.

Here's the issue: if your panning is smooth (updated every 1ms), but `@center_changed` is called only every 10ms, when you pan the following will occur in order:
1. *pan*
2. `@center_changed`
3. `mapCenter = $event.latLng`
4. `setCenter(mapCenter)`

By the time (4) happens, if you had panned to a different location than `mapCenter`, you will be snapped back to `mapCenter`. That's why the bug occurs. Most people don't have (3) so we don't get this bug.

The key is that, in reality you only want to call step (4) when the change of center was **not** triggered by a pan. When you're panning the map, you only want to call steps 1-3. When you are editing the input box, you only want steps 4.

**Comment by xkjyeah** [comment] 2018-02-16 06:52
Hi, please refer to the code here:
https://github.com/xkjyeah/vue-google-maps/commit/29091fb36a8c37ad25b4cfc66b61d0258a9f6423

This uses the `reportedMapCenter` method.

In this particular example, it is doubly clear why there cannot be two-way binding between the parent, map and street view panorama.

In general, although all street view panorama positions are also valid map positions, the converse is not true -- there are many map positions for which there are no valid street view panoramas. Therefore, it is *impossible* for them to be mapped to the same coordinates with full two-way binding (in any case, Vue's two-way binding is actually a wrapper around `:value` and `@change`/`@input`).

The solution is to send down the synchronization instructions only at specific events (`@change` for text box, `@dragend` / `@zoom_changed` for map, `@position_changed` for panoramas.

**Comment by JoseGoncalves** [comment] 2018-02-16 08:40
Hi, your updated example performs the job correctly and shows the way to do this two-way binding.

I would only suggest to use `@idle` event instead of `@dragend` to call the `sync()` method in the map, because this will allow the map to stop "naturally" after the drag, and not immediately after you stop pressing the mouse button.

**Comment by JoseGoncalves** [comment] 2018-02-16 08:52
You could also simplify your example by removing the `getCenter()` in the `@center_changed` event and `getPosition()` in the `@position_changed` event as this is already done inside the component, i.e., you can do simply:

```html
    <gmap-map :center="mapCenter" :zoom="12"
      ref="map"
      @center_changed="updateCenter"
      @idle="sync"
      class="map-container">
    </gmap-map>

    <gmap-street-view-panorama
      :position="mapCenter"
      ref="pano"
      @position_changed="updateCenter"
      :pov="pov"
      class="map-container">
    </gmap-street-view-panorama>
```

**Closed as completed** 2018-03-17 06:47 UTC

**Comment by spectra10008** [comment] 2020-03-31 08:35
Problem: The drag is not smooth, it only moves pixel by pixel. Already try using idle and still not working.

What can i do?

**Comment by TravisRick** [comment] 2021-12-17 11:08
> Problem: The drag is not smooth, it only moves pixel by pixel. Already try using idle and still not working.
> 
> What can i do?

I use a [debounce](https://lodash.com/docs/4.17.15#debounce) in order to solve this problem. Example:

    import debounce from 'lodash/debounce'

    const sync = debounce(() => {
      mapCenter.value = reportedMapCenter.value
    }, 300)
